apiVersion: apps/v1
kind: Deployment
metadata:
  name: soyka-app
  namespace: staging
  labels:
    app: soyka

spec:
  selector:
    matchLabels:
      app: soyka

  replicas: 1

  template:
    metadata:
      labels:
        app: soyka
      annotations:

    spec:
      restartPolicy: Always
      containers:
        - name: soyka
          image: docker.io/dejankovacevic/soyka:latest
          imagePullPolicy: Always

          env:
            - name: DB_URL
              value: jdbc:postgresql://10.64.33.3:5432/soyka

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: db-user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: db-password

          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: soyka-service
  namespace: staging
spec:
  selector:
    app: soyka
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
